# Generated by Django 2.2.22 on 2021-05-06 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateData',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('gender', models.CharField(max_length=1)),
                ('passport_no', models.CharField(max_length=12)),
                ('birth_date', models.DateField()),
                ('phone_no', models.CharField(max_length=12)),
                ('education_info', models.CharField(max_length=12)),
                ('health_info', models.CharField(max_length=12)),
                ('check_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='IndividualBusinessman',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('passport_no', models.CharField(max_length=12)),
                ('birth_date', models.DateField()),
                ('phone_no', models.CharField(max_length=12)),
                ('individual_no', models.CharField(max_length=12)),
                ('bank_account', models.CharField(max_length=12)),
                ('health_info', models.CharField(max_length=12)),
                ('contract_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='RequesterData',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('birth_date', models.CharField(max_length=12)),
                ('passport_no', models.CharField(max_length=12)),
                ('phone_no', models.CharField(max_length=12)),
                ('check_date', models.CharField(max_length=12)),
            ],
        ),
    ]
