# Generated by Django 2.2.23 on 2021-05-20 18:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individualbusinessman',
            name='passport_no',
        ),
        migrations.AlterField(
            model_name='candidatedata',
            name='education_info',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='candidatedata',
            name='health_info',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='candidatedata',
            name='passport_no',
            field=models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
        migrations.AlterField(
            model_name='candidatedata',
            name='phone_no',
            field=models.CharField(max_length=11, validators=[django.core.validators.MinLengthValidator(11)]),
        ),
        migrations.AlterField(
            model_name='individualbusinessman',
            name='health_info',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='individualbusinessman',
            name='phone_no',
            field=models.CharField(max_length=11, validators=[django.core.validators.MinLengthValidator(11)]),
        ),
        migrations.AlterField(
            model_name='requesterdata',
            name='birth_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='requesterdata',
            name='check_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='requesterdata',
            name='passport_no',
            field=models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
        migrations.AlterField(
            model_name='requesterdata',
            name='phone_no',
            field=models.CharField(max_length=11, validators=[django.core.validators.MinLengthValidator(11)]),
        ),
    ]
